# Generated by Django 4.2.1 on 2023-05-09 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('is_named', models.BooleanField(default=False)),
                ('named_url_kwargs', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menu',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.menu'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together={('name', 'menu')},
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='menu_name',
        ),
    ]
